version: '2'
services:
    otc:
        build: .
        environment:
            - DB_NAME=mock_otc_prod
            - DB_HOST=mongodb
            - DB_PORT=27015
        container_name: "otc"
        ports:
            - 8000:8000
        depends_on:
            - mongodb
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    mongodb:
        image: "mongo"
        container_name: "mongodb"
        volumes:
            - ./mongodb:/data/db
        ports:
            - 27015:27015
        command: mongod --port 27015
